### ISSUE TITLE
The following assertion was thrown building Image(image:

### ISSUE THREAD

**Issue by vadimlukutin** [robert-luoqing/flutter_list_view#27]
On FlutterListView after onRefresh. On image list have error. 
Other images loaded successful.

[ +274 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following assertion was thrown building Image(image:
                    NetworkImage("http://example.com/images/___res_w1280_q70/links/google.jpg", scale: 1.0),
                    frameBuilder: null, loadingBuilder: Closure: (BuildContext, Widget, ImageChunkEvent?) => Widget,
                    width: 104.0, height: 104.0, fit: cover, alignment: Alignment.center, this.excludeFromSemantics:
                    false, filterQuality: low, dependencies: [Directionality, MediaQuery, _EffectiveTickerMode,
                    _LocalizationsScope-[GlobalKey#0a9cc], _ViewScope], state: _ImageState#5e0c0(stream:
                    ImageStream#1f2e0(MultiFrameImageStreamCompleter#5a200, unresolved, 2 listeners), pixels: null,
                    loadingProgress: ImageChunkEvent#8378e(cumulativeBytesLoaded: 28766, expectedTotalBytes: 28766),
                    frameNumber: null, wasSynchronouslyLoaded: false)):
                    'package:flutter/src/rendering/object.dart': Failed assertion: line 2103 pos 14:
                    '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.
                    
                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md
                    
                    The relevant error-causing widget was:
                      Image
                      Image:file:///home/user/FlutterProjects/prj/ui/lib/src/extra/src/image_load.dart:95:22
                    
                    When the exception was thrown, this was the stack:
                    #2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2103:14)
                    #3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #4      RenderObject.dropChild (package:flutter/src/rendering/object.dart:1717:5)
                    #5      ContainerRenderObjectMixin.remove (package:flutter/src/rendering/object.dart:4104:5)
                    #6      MultiChildRenderObjectElement.removeRenderObjectChild (package:flutter/src/widgets/framework.dart:6525:18)
                    #7      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:6278:37)
                    #8      Element.deactivateChild (package:flutter/src/widgets/framework.dart:4012:11)
                    #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3697:9)
                    #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
                    #11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
                    #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
                    #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
                    #14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
                    #15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
                    #16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
                    #17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
                    #18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
                    #19     _invoke (dart:ui/hooks.dart:142:13)
                    #20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
                    #21     _drawFrame (dart:ui/hooks.dart:112:31)
                    (elided 2 frames from class _AssertionError)
                    
                    ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by vadimlukutin** [comment]
Helped wrap on SizedBox
